version: '3.9'

services:
  app:
    container_name: "credit_project"
    hostname: credit_project
    depends_on: [db]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: bash -c "python credit_project/manage.py makemigrations && python credit_project/manage.py migrate && python credit_project/manage.py runserver 0.0.0.0:8000"

  db:
    hostname: pghost
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DB = postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: